name: New pull request received

on: [pull_request, workflow_dispatch]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install -U pip pipenv invoke
          inv env.init-dev --no-pre-commit

      - name: Run pre-commit hooks
        run: |
          inv run-pre-commit-hooks
